---
sudo:     false
language: ruby
cache:    bundler
before_install:
  - gem install bundler --no-document
  - gem update --system
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - 2.3.0
  - 2.7.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
